kotlin.code.style=official

# Gradle
org.gradle.jvmargs=-Xmx8192M -Dfile.encoding=UTF-8 -Dkotlin.daemon.jvm.options\="-Xmx8192M"
org.gradle.configuration-cache=true

# Android
android.nonTransitiveRClass=true
android.useAndroidX=true
android.experimental.kmp.enableAndroidResources=true
android.experimental.kmp.enableCompose=true

# Kotlin Multiplatform
kotlin.mpp.enableCInteropCommonization=true
# disable compiler daemon (due to Room - KSP)
kotlin.native.disableCompilerDaemon = true

# Versioning
versionName=1.1.0-beta03
buildNumber=110
