name: release-beta

on:
  push:
    tags:
      - '*.*.*-beta*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Create Sentry config file
        env:
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
        run: |
          echo 'sentry_dsn=$SENTRY_DSN\n' > core/utils/build.properties

      - name: Decode keystore
        env:
          ENCODED_STRING: ${{ secrets.KEYSTORE_BASE_64 }}
        run: |
          echo $ENCODED_STRING > keystore-b64.txt
          base64 -d keystore-b64.txt > keystore.jks

      - name: Build release APK
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        run: ./gradlew :composeApp:assembleRelease --stacktrace

      - name: Create Github release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          prerelease: true
          files: |
            composeApp/build/outputs/apk/release/RaccoonForFriendica-release.apk
