name: tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v5

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.10.2

      - name: Create Sentry config file
        env:
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
        run: |
          echo sentry_dsn=$SENTRY_DSN > core/utils/build.properties

      - name: Create Translation API config file
        env:
          TRANSLATION_API_URL: ${{ secrets.INNER_TRANSLATION_API_URL }}
        run: |
          echo inner_translation_api_url=$TRANSLATION_API_URL > core/api/build.properties

      - name: Decode keystore
        env:
          ENCODED_STRING: ${{ secrets.KEYSTORE_BASE_64 }}
        run: |
          echo $ENCODED_STRING > keystore-b64.txt
          base64 -d keystore-b64.txt > composeApp/keystore.jks

      - name: Run unit tests
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        run: ./gradlew testDebugUnitTest

      - name: Generate code coverage
        run: ./gradlew :composeApp:koverXmlReportDebug

      - name: Upload coverage report
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: false
          files: ./composeApp/build/reports/kover/reportDebug.xml
          flags: unittests
          name: raccoon4friendica
          token: ${{ secrets.CODECOV_TOKEN }}
